### ISSUE TITLE
Collections to add on v1

### ISSUE THREAD

**Issue by fepvenancio** [VerisLabs/unlockd#144]
https://docs.google.com/spreadsheets/d/1wtntY8lNJD69Zn2dSwSj2gDst5LeiZp4B-mvjp3B9aw/edit#gid=0

Between row 30 (Collections) DeGods till row 40 Mavia Land should be added to frontend.
For Image pick a random number if u can't find the proper one.

**Comment by federicolopezeikilis** [comment]
Done and deployed
