### ISSUE TITLE
Add The Captainz

### ISSUE THREAD

**Issue by fepvenancio** [VerisLabs/unlockd#149]
We need to add The Captainz to the frontend (backend is done, price endpoint working).
proxy address: 0x769272677faB02575E84945F03Eca517ACc544Cc 
uNFT: 0x353d339d73D2b8627E28ad694971272a21F81F97

![image](https://github.com/UnlockdFinance/unlockd/assets/26207020/8b9a335a-99ee-4053-8597-851a9c4125f4)

**Comment by federicolopezeikilis** [comment]
Done
